### ISSUE TITLE
Addons DB version

### ISSUE THREAD

**Issue by pkntl** [idolpx/script.idolpx.installer#3]
I just installed this in v18 (Leia) and I was getting a DB write error. Turns out that Leia still uses the addons database version `27` instead of `28`. Thought you should know.

**Comment by idolpx** [comment]
Hmmm... ok.  I haven't tested on Leia yet.  Thanks for the heads up.  :)

**Comment by idolpx** [comment]
Made the adjustment.  Thanks!
